language: python

python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget https://www4.stat.ncsu.edu/~boos/var.select/diabetes.rwrite1.txt
 - mv diabetes.rwrite1.txt diabetes.data

script:
 - python3 hw7.py --help
 - python3 hw7.py diabetes.data -H
 - python3 hw7.py diabetes.data -H -p bmi weight
 - python3 hw7.py diabetes.data -H -s glu
 - python3 hw7.py diabetes.data -H -i y glu 220
